remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: /assets/img/portret.jpg
title: Rutger Dirks
author: Rutger Dirks
description: <a href="https://www.linkedin.com/in/rutger-f-dirks/ " target="_blank">LinkedIn tab</a>
Engineer in Automation and Robotics | Portfolio of my projects
permalink: /:categories/:year/:month/:day/:title:output_ext
