remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
logo: docs/assets/img/portret.jpg
title: Rutger Dirks Portfolio
author: Rutger Dirks
description: An overview of the projects I contributed to.
permalink: /:categories/:year/:month/:day/:title:output_ext
